NuGetSwitcher: NuGetSwitcher.Core.Switch.LibrarySwitch Class Reference
NuGetSwitcher.Core.Switch.LibrarySwitch Class Reference
Public Member Functions
LibrarySwitch (ReferenceType type, IOptionProvider optionProvider, IProjectProvider projectHelper, IMessageProvider messageHelper)
override IEnumerable< string > Switch ()
Replaces PackageReference references marked with the Temp attribute to Reference. Transitive dependencies will be included.
Public Member Functions inherited from NuGetSwitcher.Core.Switch.ProjectSwitch
ProjectSwitch (ReferenceType type, IOptionProvider optionProvider, IProjectProvider projectHelper, IMessageProvider messageHelper)
override IEnumerable< string > Switch ()
Replaces PackageReference references marked with the Temp attribute to ProjectReference. Transitive dependencies will be included.
virtual void SwitchSysDependency (IProjectReference reference, LockFileTargetLibrary library)
Includes references to the GAC assemblies listed in the FrameworkAssemblies section of the lock file.
virtual void SwitchPkgDependency (IProjectReference reference, LockFileTargetLibrary library, string absolutePath)
Includes implicit, explicit project references listed in the Dependencies section of the lock file.
Additional Inherited Members
Protected Member Functions inherited from NuGetSwitcher.Core.Switch.ProjectSwitch
virtual void AddToSolution (string solution, IEnumerable< string > projects)
Protected Member Functions inherited from NuGetSwitcher.Core.Abstract.AbstractSwitch
AbstractSwitch (ReferenceType type, IOptionProvider optionProvider, IProjectProvider projectProvider, IMessageProvider messageProvider)
virtual LockFile GetLockFile (IProjectReference reference)
Returns the LockFile object that represents the contents of project.assets.json. Used to identify project dependencies.
virtual LockFileTarget GetProjectTarget (IProjectReference reference)
Returns the LockFileTarget section for a project TFM from the lock file provided by LockFile.
virtual void IterateAndExecute (IEnumerable< IProjectReference > references, Action< IProjectReference, LockFileTargetLibrary, string > func)
Iterates through the dependencies provided in the lock file and matches against items found in the directories listed in the configuration file. For each matched item, the passed delegate is executed.
virtual Dictionary< string, string > AdaptMetadata (string unevaluatedInclude, Dictionary< string, string > metadata)
Performs metadata validation and filling with data common to all references.
virtual bool AddReference (IProjectReference reference, ReferenceType type, string unevaluatedInclude, Dictionary< string, string > metadata)
Adds reference to the project. It is assumed that the original reference has been removed earlier.
Properties inherited from NuGetSwitcher.Core.Abstract.AbstractSwitch
ReferenceType Type [get]
IOptionProvider OptionProvider [get, set]
IProjectProvider ProjectProvider [get, set]
IMessageProvider MessageProvider [get, set]
Detailed Description
Definition at line 15 of file LibrarySwitch.cs.
Constructor & Destructor Documentation
LibrarySwitch()
NuGetSwitcher.Core.Switch.LibrarySwitch.LibrarySwitch (ReferenceType type, IOptionProvider optionProvider, IProjectProvider projectHelper, IMessageProvider messageHelper)
Definition at line 17 of file LibrarySwitch.cs.
                                                                                                                                                  : base(type, optionProvider, projectHelper, messageHelper)
         { }
Member Function Documentation
Switch()
override IEnumerable<string> NuGetSwitcher.Core.Switch.LibrarySwitch.Switch () virtual
Replaces PackageReference references marked with the Temp attribute to Reference. Transitive dependencies will be included.
Exceptions
SwitcherFileNotFoundException
FileNotFoundException
ArgumentException
Implements NuGetSwitcher.Core.Abstract.AbstractSwitch.
Definition at line 31 of file LibrarySwitch.cs.
         {
             void Executor(IProjectReference reference, LockFileTargetLibrary library, string absolutePath)
             {
                 SwitchSysDependency(reference, library);
                 SwitchPkgDependency(reference, library, absolutePath);
             }
             IterateAndExecute(ProjectProvider.GetLoadedProject(), Executor);
             return default;
         }
References NuGetSwitcher.Interface.Contract.IProjectProvider.GetLoadedProject(), NuGetSwitcher.Core.Abstract.AbstractSwitch.IterateAndExecute(), NuGetSwitcher.Core.Abstract.AbstractSwitch.ProjectProvider, NuGetSwitcher.Core.Switch.ProjectSwitch.SwitchPkgDependency(), and NuGetSwitcher.Core.Switch.ProjectSwitch.SwitchSysDependency().
The documentation for this class was generated from the following file:
NuGetSwitcher.Core/Switch/LibrarySwitch.cs