NuGetSwitcher: NuGetSwitcher.Core.Switch.ProjectSwitch Class Reference
NuGetSwitcher.Core.Switch.ProjectSwitch Class Reference
Public Member Functions
ProjectSwitch (IProjectHelper projectHelper, IMessageHelper messageHelper)
virtual void SwithPackage (ReadOnlyDictionary< string, string > projectPaths)
Switches references to NuGet packages to references to projects, given implicit / transitive dependencies.
virtual void SwitchSysDependency (ProjectReference reference, LockFileTargetLibrary library)
Includes references to the GAC assemblies listed in the FrameworkAssemblies section of the lock file.
virtual void SwitchPkgDependency (ProjectReference reference, LockFileTargetLibrary library, ref HashSet< string > toInclude, string absolutePath)
Includes references to the project. If library is null, then dependency is considered as implicit, otherwise as explicit.
virtual void SwitchPkgDependency (ProjectReference reference, LockFileTargetLibrary library, ref HashSet< string > toInclude, ReadOnlyDictionary< string, string > projectPaths)
Includes references presented as implicit project dependencies.
virtual void IncludeProject (IEnumerable< string > projects)
Includes a set of passed projects in the solution.
Static Public Member Functions
static LockFile GetLockFile (ProjectReference reference)
Returns the LockFile object that represents the contents of project.assets.json. Used to identify project dependencies.
static LockFileTarget GetProjectTarget (ProjectReference reference)
Returns the LockFileTarget section for a project TFM from the lock file provided by LockFile.
Protected Member Functions
virtual void AddReference (ref ProjectReference reference, ReferenceType type, string unevaluatedInclude, Dictionary< string, string > metadata)
Adds reference to the project. It is assumed that the original reference has been removed earlier.
Properties
IProjectHelper ProjectHelper [get, set]
IMessageHelper MessageHelper [get, set]
Detailed Description
Definition at line 24 of file ProjectSwitch.cs.
Constructor & Destructor Documentation
ProjectSwitch()
NuGetSwitcher.Core.Switch.ProjectSwitch.ProjectSwitch (IProjectHelper projectHelper, IMessageHelper messageHelper)
Definition at line 38 of file ProjectSwitch.cs.
         {
             ProjectHelper = projectHelper;
             MessageHelper = messageHelper;
         }
Member Function Documentation
AddReference()
virtual void NuGetSwitcher.Core.Switch.ProjectSwitch.AddReference (ref ProjectReference reference, ReferenceType type, string unevaluatedInclude, Dictionary< string, string > metadata) protected virtual
Adds reference to the project. It is assumed that the original reference has been removed earlier.
Parameters
type All except ReferenceType.PackageReference
Parameters
unevaluatedInclude Must contain the assembly name or the absolute path to the project.
https://github.com/Microsoft/msbuild/issues/3923.
Definition at line 216 of file ProjectSwitch.cs.
         {
             if (reference.MsbProject.GetItemsByEvaluatedInclude(unevaluatedInclude).Any())
             {
                 return;
             }
             switch (type)
             {
                 case ReferenceType.ProjectReference:
                     ;
                     break;
                 case ReferenceType.Reference:
                     ;
                     break;
                 default:
                     throw new SwitcherException(reference.MsbProject, $"Reference type not supported: { type }");
             }
             reference.MsbProject.AddItem(type.ToString(), unevaluatedInclude, metadata);
             MessageHelper.AddMessage(reference.MsbProject.FullPath, $"Dependency: { Path.GetFileName(unevaluatedInclude) } has been added. Type: { type }", TaskErrorCategory.Message);
         }
References NuGetSwitcher.Helper.MessageHelper.AddMessage().
GetLockFile()
static LockFile NuGetSwitcher.Core.Switch.ProjectSwitch.GetLockFile (ProjectReference reference) static
Returns the LockFile object that represents the contents of project.assets.json. Used to identify project dependencies.
Exceptions
SwitcherFileNotFoundException
Definition at line 51 of file ProjectSwitch.cs.
         {
             return LockFileUtilities.GetLockFile(reference.LockFile, NullLogger.Instance);
         }
References NuGetSwitcher.Helper.Entity.ProjectReference.LockFile.
GetProjectTarget()
static LockFileTarget NuGetSwitcher.Core.Switch.ProjectSwitch.GetProjectTarget (ProjectReference reference) static
Returns the LockFileTarget section for a project TFM from the lock file provided by LockFile.
Exceptions
SwitcherFileNotFoundException
Definition at line 63 of file ProjectSwitch.cs.
         {
             return GetLockFile(reference).GetTarget(new NuGetFramework(reference.TFI, new Version(reference.TFV), string.Empty), null);
         }
References NuGetSwitcher.Core.Switch.ProjectSwitch.GetLockFile(), NuGetSwitcher.Helper.Entity.ProjectReference.TFI, and NuGetSwitcher.Helper.Entity.ProjectReference.TFV.
IncludeProject()
virtual void NuGetSwitcher.Core.Switch.ProjectSwitch.IncludeProject (IEnumerable< string > projects) virtual
Includes a set of passed projects in the solution.
Parameters
projects Absolute paths to project files without duplicates.
Definition at line 249 of file ProjectSwitch.cs.
         {
             EnvDTE.DTE dte = Package.GetGlobalService(typeof(EnvDTE.DTE)) as EnvDTE.DTE;
             try
             {
                 foreach (string project in projects)
                 {
                     dte.Solution.AddFromFile(project, false);
                 }
                 dte.Solution.SaveAs(dte.Solution.FileName);
             }
             catch (Exception exception)
             {
                 MessageHelper.AddMessage(exception);
             }
         }
References NuGetSwitcher.Helper.MessageHelper.AddMessage().
SwitchPkgDependency() [1/2]
virtual void NuGetSwitcher.Core.Switch.ProjectSwitch.SwitchPkgDependency (ProjectReference reference, LockFileTargetLibrary library, ref HashSet< string > toInclude, ReadOnlyDictionary< string, string > projectPaths) virtual
Includes references presented as implicit project dependencies.
Exceptions
SwitcherException
Implicit dependencies mean transitive.
Definition at line 186 of file ProjectSwitch.cs.
         {
             foreach (PackageDependency dependency in library.Dependencies)
             {
                 if (projectPaths.TryGetValue(dependency.Id, out string absolutePath))
                 {
                     SwitchPkgDependency(reference, null, ref toInclude, absolutePath);
                 }
             }
         }
References NuGetSwitcher.Core.Switch.ProjectSwitch.SwitchPkgDependency().
SwitchPkgDependency() [2/2]
virtual void NuGetSwitcher.Core.Switch.ProjectSwitch.SwitchPkgDependency (ProjectReference reference, LockFileTargetLibrary library, ref HashSet< string > toInclude, string absolutePath) virtual
Includes references to the project. If library is null, then dependency is considered as implicit, otherwise as explicit.
Exceptions
SwitcherException
Implicit dependencies mean transitive.
Definition at line 132 of file ProjectSwitch.cs.
         {
             Dictionary<string, string> metadata = new
             Dictionary<string, string>(4)
             {
                 { "Type", "Temp" }
             };
             ProjectItem item;
             /*
              * References can be represented by several values in
              * an ItemGroup, for example, when included using the
              * Condition attribute.
              */
             ICollection<ProjectItem> items = reference.MsbProject.GetItemsByEvaluatedInclude(library?.Name ?? string.Empty);
             if (!items.Any())
             {
                 if (library != default)
                 {
                     return;
                 }
                 metadata.Add("Name", Path.GetFileNameWithoutExtension(absolutePath));
             }
             else
             {
                 item = items.First();
                 metadata.Add("Name"   , item.EvaluatedInclude);
                 metadata.Add("Include", item.EvaluatedInclude);
                 metadata.Add("Version", item.
                     GetMetadataValue("Version"));
                 reference.MsbProject.RemoveItems(items);
             }
             AddReference(ref reference, ReferenceType.ProjectReference, absolutePath, metadata);
             toInclude.Add(absolutePath);
         }
References NuGetSwitcher.Core.Switch.ProjectSwitch.AddReference(), NuGetSwitcher.Helper.Entity.ProjectReference.MsbProject, and NuGetSwitcher.Helper.Entity.ProjectReference.ProjectReference().
SwitchSysDependency()
virtual void NuGetSwitcher.Core.Switch.ProjectSwitch.SwitchSysDependency (ProjectReference reference, LockFileTargetLibrary library) virtual
Includes references to the GAC assemblies listed in the FrameworkAssemblies section of the lock file.
Definition at line 107 of file ProjectSwitch.cs.
         {
             Dictionary<string, string> metadata = new
             Dictionary<string, string>(4)
             {
                 { "Type", "Temp" }
             };
             foreach (string assembly in library.FrameworkAssemblies)
             {
                 AddReference(ref reference, ReferenceType.Reference, assembly, metadata);
             }
         }
References NuGetSwitcher.Core.Switch.ProjectSwitch.AddReference().
SwithPackage()
virtual void NuGetSwitcher.Core.Switch.ProjectSwitch.SwithPackage (ReadOnlyDictionary< string, string > projectPaths) virtual
Switches references to NuGet packages to references to projects, given implicit / transitive dependencies.
Exceptions
SwitcherFileNotFoundException
Implements NuGetSwitcher.Core.Switch.IProjectSwtich.
Definition at line 75 of file ProjectSwitch.cs.
         {
             MessageHelper.Clear();
             IEnumerable<ProjectReference> references = ProjectHelper.GetLoadedProject();
             HashSet<string> toInclude = new
             HashSet<string>();
             foreach (ProjectReference reference in references)
             {
                 foreach (LockFileTargetLibrary library in GetProjectTarget(reference).Libraries)
                 {
                     if (projectPaths.TryGetValue(library.Name, out string absolutePath))
                     {
                         SwitchSysDependency(reference, library);
                         SwitchPkgDependency(reference, library, ref toInclude, absolutePath);
                         SwitchPkgDependency(reference, library, ref toInclude, projectPaths);
                     }
                 }
                 reference.Save();
             }
             IncludeProject(toInclude.Except(references.Select(r => r.MsbProject.FullPath)));
         }
References NuGetSwitcher.Helper.MessageHelper.Clear(), NuGetSwitcher.Helper.ProjectHelper.GetLoadedProject(), NuGetSwitcher.Core.Switch.ProjectSwitch.GetProjectTarget(), NuGetSwitcher.Core.Switch.ProjectSwitch.IncludeProject(), NuGetSwitcher.Helper.Entity.ProjectReference.Save(), NuGetSwitcher.Core.Switch.ProjectSwitch.SwitchPkgDependency(), and NuGetSwitcher.Core.Switch.ProjectSwitch.SwitchSysDependency().
Property Documentation
MessageHelper
IMessageHelper NuGetSwitcher.Core.Switch.ProjectSwitch.MessageHelper get set protected
Definition at line 32 of file ProjectSwitch.cs.
         {
             get;
             set;
         }
ProjectHelper
IProjectHelper NuGetSwitcher.Core.Switch.ProjectSwitch.ProjectHelper get set protected
Definition at line 26 of file ProjectSwitch.cs.
         {
             get;
             set;
         }
The documentation for this class was generated from the following file:
ProjectSwitch.cs