NuGetSwitcher: NuGetSwitcher.Core.Switch.PackageSwitch Class Reference
NuGetSwitcher.Core.Switch.PackageSwitch Class Reference
Public Member Functions
PackageSwitch (ReferenceType type, IOptionProvider optionProvider, IProjectProvider projectHelper, IMessageProvider messageHelper)
override IEnumerable< string > Switch ()
Replaces ProjectReference references marked with the Temp attribute to PackageReference.
virtual void SwitchDependency (IProjectReference reference, ReferenceType type)
Removes references that have the Temp attribute and which were added from the Dependencies and FrameworkAssemblies sections of the lock file.
Protected Member Functions
virtual IReadOnlyList< ProjectItem > GetTempItem (IProjectReference reference, ReferenceType type)
Returns references with the passed type and marked with the Temp attribute.
Protected Member Functions inherited from NuGetSwitcher.Core.Abstract.AbstractSwitch
AbstractSwitch (ReferenceType type, IOptionProvider optionProvider, IProjectProvider projectProvider, IMessageProvider messageProvider)
virtual LockFile GetLockFile (IProjectReference reference)
Returns the LockFile object that represents the contents of project.assets.json. Used to identify project dependencies.
virtual LockFileTarget GetProjectTarget (IProjectReference reference)
Returns the LockFileTarget section for a project TFM from the lock file provided by LockFile.
virtual void IterateAndExecute (IEnumerable< IProjectReference > references, Action< IProjectReference, LockFileTargetLibrary, string > func)
Iterates through the dependencies provided in the lock file and matches against items found in the directories listed in the configuration file. For each matched item, the passed delegate is executed.
virtual Dictionary< string, string > AdaptMetadata (string unevaluatedInclude, Dictionary< string, string > metadata)
Performs metadata validation and filling with data common to all references.
virtual bool AddReference (IProjectReference reference, ReferenceType type, string unevaluatedInclude, Dictionary< string, string > metadata)
Adds reference to the project. It is assumed that the original reference has been removed earlier.
Additional Inherited Members
Properties inherited from NuGetSwitcher.Core.Abstract.AbstractSwitch
ReferenceType Type [get]
IOptionProvider OptionProvider [get, set]
IProjectProvider ProjectProvider [get, set]
IMessageProvider MessageProvider [get, set]
Detailed Description
Definition at line 16 of file PackageSwitch.cs.
Constructor & Destructor Documentation
PackageSwitch()
NuGetSwitcher.Core.Switch.PackageSwitch.PackageSwitch (ReferenceType type, IOptionProvider optionProvider, IProjectProvider projectHelper, IMessageProvider messageHelper)
Definition at line 18 of file PackageSwitch.cs.
                                                                                                                                                  : base(type, optionProvider, projectHelper, messageHelper)
         { }
Member Function Documentation
GetTempItem()
virtual IReadOnlyList<ProjectItem> NuGetSwitcher.Core.Switch.PackageSwitch.GetTempItem (IProjectReference reference, ReferenceType type) protected virtual
Returns references with the passed type and marked with the Temp attribute.
Definition at line 78 of file PackageSwitch.cs.
         {
             return reference.MsbProject.GetItems(type.ToString()).Where(i => i.HasMetadata("Temp")).ToImmutableList();
         }
References NuGetSwitcher.Interface.Entity.IProjectReference.MsbProject.
Switch()
override IEnumerable<string> NuGetSwitcher.Core.Switch.PackageSwitch.Switch () virtual
Replaces ProjectReference references marked with the Temp attribute to PackageReference.
Exceptions
SwitcherException
Implements NuGetSwitcher.Core.Abstract.AbstractSwitch.
Definition at line 27 of file PackageSwitch.cs.
         {
             MessageProvider.Clear();
             foreach (IProjectReference reference in ProjectProvider.GetLoadedProject())
             {
                 SwitchDependency(reference, ReferenceType.Reference);
                 SwitchDependency(reference, ReferenceType.ProjectReference);
                 reference.Save();
             }
             return default;
         }
References NuGetSwitcher.Interface.Contract.IMessageProvider.Clear(), NuGetSwitcher.Interface.Contract.IProjectProvider.GetLoadedProject(), NuGetSwitcher.Core.Abstract.AbstractSwitch.MessageProvider, NuGetSwitcher.Core.Abstract.AbstractSwitch.ProjectProvider, NuGetSwitcher.Interface.Entity.IProjectReference.Save(), and NuGetSwitcher.Core.Switch.PackageSwitch.SwitchDependency().
SwitchDependency()
virtual void NuGetSwitcher.Core.Switch.PackageSwitch.SwitchDependency (IProjectReference reference, ReferenceType type) virtual
Removes references that have the Temp attribute and which were added from the Dependencies and FrameworkAssemblies sections of the lock file.
Definition at line 49 of file PackageSwitch.cs.
         {
             foreach (ProjectItem item in GetTempItem(reference, type))
             {
                 // Implicit.
                 if (!item.HasMetadata("Version"))
                 {
                     reference.MsbProject.RemoveItem(item);
                 }
                 // Explicit.
                 else
                 {
                     item.UnevaluatedInclude = item.GetMetadataValue("Temp");
                     item.RemoveMetadata("Temp");
                     item.RemoveMetadata("Name");
                     item.ItemType = Type.ToString();
                 }
                 MessageProvider.AddMessage(reference.UniqueName, $"Dependency: { Path.GetFileNameWithoutExtension(item.EvaluatedInclude) } has been switched back. Type: { Type }", MessageCategory.ME);
             }
         }
References NuGetSwitcher.Interface.Contract.IMessageProvider.AddMessage(), NuGetSwitcher.Core.Switch.PackageSwitch.GetTempItem(), NuGetSwitcher.Core.Abstract.AbstractSwitch.MessageProvider, NuGetSwitcher.Interface.Entity.IProjectReference.MsbProject, NuGetSwitcher.Core.Abstract.AbstractSwitch.Type, and NuGetSwitcher.Interface.Entity.IProjectReference.UniqueName.
The documentation for this class was generated from the following file:
NuGetSwitcher.Core/Switch/PackageSwitch.cs