NuGetSwitcher: NuGetSwitcher.VSIXService.Message.VsixMessageProvider Class Reference
NuGetSwitcher.VSIXService.Message.VsixMessageProvider Class Reference
Public Member Functions
VsixMessageProvider (IVsSolution vsSolution, ErrorListProvider errorList)
virtual void AddMessage (string message, MessageCategory category, [CallerMemberName] string caller="")
Displays a message with the specified type in the associated GUI tab.
virtual void AddMessage (string project, string message, MessageCategory category, [CallerMemberName] string caller="")
Displays a message with the specified type in the associated GUI tab. This overload fills the Project column.
virtual void AddMessage (Exception exception, [CallerMemberName] string caller="")
Displays a message with the specified type in the associated GUI tab.
virtual void AddMessage (string project, Exception exception, [CallerMemberName] string caller="")
Displays a message with the specified type in the associated GUI tab. This overload fills the Project column.
virtual void AddMessage (SwitcherException exception, [CallerMemberName] string caller="")
Displays a message with the specified type in the associated GUI tab.
virtual void Clear ()
Clears previously created tasks in ErrorListProvider.
Protected Member Functions
virtual IVsHierarchy GetProjectHierarchyItem (string project)
Returns the project in the solution, given a unique name.
Properties
IVsSolution VsSolution [get, set]
ErrorListProvider ErrorList [get, set]
Detailed Description
Definition at line 13 of file VsixMessageProvider.cs.
Constructor & Destructor Documentation
VsixMessageProvider()
NuGetSwitcher.VSIXService.Message.VsixMessageProvider.VsixMessageProvider (IVsSolution vsSolution, ErrorListProvider errorList)
Definition at line 27 of file VsixMessageProvider.cs.
         {
             VsSolution = vsSolution;
             ErrorList = errorList;
         }
References NuGetSwitcher.VSIXService.Message.VsixMessageProvider.ErrorList, and NuGetSwitcher.VSIXService.Message.VsixMessageProvider.VsSolution.
Member Function Documentation
AddMessage() [1/5]
virtual void NuGetSwitcher.VSIXService.Message.VsixMessageProvider.AddMessage (Exception exception, [CallerMemberName] string caller = "") virtual
Displays a message with the specified type in the associated GUI tab.
Implements NuGetSwitcher.Interface.Contract.IMessageProvider.
Definition at line 65 of file VsixMessageProvider.cs.
         {
             SwitcherException se = exception as SwitcherException;
             if (se == default)
             {
                 AddMessage(exception.Message, MessageCategory.ER, caller);
             }
             else
             {
                 AddMessage(se);
             }
         }
References NuGetSwitcher.VSIXService.Message.VsixMessageProvider.AddMessage().
AddMessage() [2/5]
virtual void NuGetSwitcher.VSIXService.Message.VsixMessageProvider.AddMessage (string message, MessageCategory category, [CallerMemberName] string caller = "") virtual
Displays a message with the specified type in the associated GUI tab.
Implements NuGetSwitcher.Interface.Contract.IMessageProvider.
Definition at line 39 of file VsixMessageProvider.cs.
         {
             ErrorList.Tasks.Add(new ErrorTask { Text = $"Caller: { caller }. Message: { message }", ErrorCategory = (TaskErrorCategory)category });
         }
References NuGetSwitcher.VSIXService.Message.VsixMessageProvider.ErrorList.
AddMessage() [3/5]
virtual void NuGetSwitcher.VSIXService.Message.VsixMessageProvider.AddMessage (string project, Exception exception, [CallerMemberName] string caller = "") virtual
Displays a message with the specified type in the associated GUI tab. This overload fills the Project column.
Parameters
project Full path to the solution project.
Implements NuGetSwitcher.Interface.Contract.IMessageProvider.
Definition at line 90 of file VsixMessageProvider.cs.
         {
             AddMessage(project, exception.Message, MessageCategory.ER, caller);
         }
References NuGetSwitcher.VSIXService.Message.VsixMessageProvider.AddMessage().
AddMessage() [4/5]
virtual void NuGetSwitcher.VSIXService.Message.VsixMessageProvider.AddMessage (string project, string message, MessageCategory category, [CallerMemberName] string caller = "") virtual
Displays a message with the specified type in the associated GUI tab. This overload fills the Project column.
Parameters
project Full path to the solution project.
Implements NuGetSwitcher.Interface.Contract.IMessageProvider.
Definition at line 55 of file VsixMessageProvider.cs.
         {
             ErrorList.Tasks.Add(new ErrorTask { Text = $"Caller: { caller }. Message: { message }", ErrorCategory = (TaskErrorCategory)category, HierarchyItem = GetProjectHierarchyItem(project), Document = project });
         }
References NuGetSwitcher.VSIXService.Message.VsixMessageProvider.ErrorList, and NuGetSwitcher.VSIXService.Message.VsixMessageProvider.GetProjectHierarchyItem().
AddMessage() [5/5]
virtual void NuGetSwitcher.VSIXService.Message.VsixMessageProvider.AddMessage (SwitcherException exception, [CallerMemberName] string caller = "") virtual
Displays a message with the specified type in the associated GUI tab.
Implements NuGetSwitcher.Interface.Contract.IMessageProvider.
Definition at line 100 of file VsixMessageProvider.cs.
         {
             AddMessage(exception.MsbProject.FullPath, exception.Message, MessageCategory.ER, caller);
         }
References NuGetSwitcher.VSIXService.Message.VsixMessageProvider.AddMessage(), and NuGetSwitcher.Interface.Entity.Error.SwitcherException.MsbProject.
Clear()
virtual void NuGetSwitcher.VSIXService.Message.VsixMessageProvider.Clear () virtual
Clears previously created tasks in ErrorListProvider.
Implements NuGetSwitcher.Interface.Contract.IMessageProvider.
Definition at line 109 of file VsixMessageProvider.cs.
         {
             ErrorList.Tasks.Clear();
         }
References NuGetSwitcher.VSIXService.Message.VsixMessageProvider.ErrorList.
GetProjectHierarchyItem()
virtual IVsHierarchy NuGetSwitcher.VSIXService.Message.VsixMessageProvider.GetProjectHierarchyItem (string project) protected virtual
Returns the project in the solution, given a unique name.
Parameters
project Full path to the solution project.
Returns
Pointer to the IVsHierarchy interface of the project referred to by project.
https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.shell.interop.ivshierarchy.
Definition at line 131 of file VsixMessageProvider.cs.
         {
             const int S_OK = 0;
             int exitCode = VsSolution.GetProjectOfUniqueName(project, out IVsHierarchy hierarchyItem);
             if (exitCode != S_OK)
             {
                 AddMessage($"Exit code: { exitCode }", MessageCategory.ER);
             }
             return hierarchyItem;
         }
References NuGetSwitcher.VSIXService.Message.VsixMessageProvider.AddMessage(), and NuGetSwitcher.VSIXService.Message.VsixMessageProvider.VsSolution.
Property Documentation
ErrorList
ErrorListProvider NuGetSwitcher.VSIXService.Message.VsixMessageProvider.ErrorList get set protected
Definition at line 21 of file VsixMessageProvider.cs.
         {
             get;
             set;
         }
VsSolution
IVsSolution NuGetSwitcher.VSIXService.Message.VsixMessageProvider.VsSolution get set protected
Definition at line 15 of file VsixMessageProvider.cs.
         {
             get;
             set;
         }
The documentation for this class was generated from the following file:
NuGetSwitcher.VSIXService/Message/VsixMessageProvider.cs