NuGetSwitcher: NuGetSwitcher.Core.Abstract.AbstractSwitch Class Reference
NuGetSwitcher.Core.Abstract.AbstractSwitch Class Reference abstract
Public Member Functions
abstract IEnumerable< string > Switch ()
Basic operation of switching one type of reference to another.
Protected Member Functions
AbstractSwitch (ReferenceType type, IOptionProvider optionProvider, IProjectProvider projectProvider, IMessageProvider messageProvider)
virtual LockFile GetLockFile (IProjectReference reference)
Returns the LockFile object that represents the contents of project.assets.json. Used to identify project dependencies.
virtual LockFileTarget GetProjectTarget (IProjectReference reference)
Returns the LockFileTarget section for a project TFM from the lock file provided by LockFile.
virtual void IterateAndExecute (IEnumerable< IProjectReference > references, Action< IProjectReference, LockFileTargetLibrary, string > func)
Iterates through the dependencies provided in the lock file and matches against items found in the directories listed in the configuration file. For each matched item, the passed delegate is executed.
virtual Dictionary< string, string > AdaptMetadata (string unevaluatedInclude, Dictionary< string, string > metadata)
Performs metadata validation and filling with data common to all references.
virtual bool AddReference (IProjectReference reference, ReferenceType type, string unevaluatedInclude, Dictionary< string, string > metadata)
Adds reference to the project. It is assumed that the original reference has been removed earlier.
Properties
ReferenceType Type [get]
IOptionProvider OptionProvider [get, set]
IProjectProvider ProjectProvider [get, set]
IMessageProvider MessageProvider [get, set]
Detailed Description
Definition at line 18 of file AbstractSwitch.cs.
Constructor & Destructor Documentation
AbstractSwitch()
NuGetSwitcher.Core.Abstract.AbstractSwitch.AbstractSwitch (ReferenceType type, IOptionProvider optionProvider, IProjectProvider projectProvider, IMessageProvider messageProvider) protected
Definition at line 44 of file AbstractSwitch.cs.
         {
             Type = type;
             OptionProvider  = optionProvider;
             ProjectProvider = projectProvider;
             MessageProvider = messageProvider;
         }
References NuGetSwitcher.Core.Abstract.AbstractSwitch.MessageProvider, NuGetSwitcher.Core.Abstract.AbstractSwitch.OptionProvider, NuGetSwitcher.Core.Abstract.AbstractSwitch.ProjectProvider, and NuGetSwitcher.Core.Abstract.AbstractSwitch.Type.
Member Function Documentation
AdaptMetadata()
virtual Dictionary<string, string> NuGetSwitcher.Core.Abstract.AbstractSwitch.AdaptMetadata (string unevaluatedInclude, Dictionary< string, string > metadata) protected virtual
Performs metadata validation and filling with data common to all references.
See:
See also
AddReference(ProjectReference, ReferenceType, string, Dictionary<string, string>)
.
Definition at line 130 of file AbstractSwitch.cs.
         {
             if (!metadata.ContainsKey("Temp"))
             {
                 metadata.Add("Temp", unevaluatedInclude);
             }
             return metadata;
         }
AddReference()
virtual bool NuGetSwitcher.Core.Abstract.AbstractSwitch.AddReference (IProjectReference reference, ReferenceType type, string unevaluatedInclude, Dictionary< string, string > metadata) protected virtual
Adds reference to the project. It is assumed that the original reference has been removed earlier.
Parameters
unevaluatedInclude Must contain the assembly name or the absolute path to the project or Package Id.
Exceptions
SwitcherException
Returns
Returns false for duplicate unevaluatedInclude values.
Definition at line 158 of file AbstractSwitch.cs.
         {
             bool output = true;
             switch (type)
             {
                 case ReferenceType.ProjectReference:
                 case ReferenceType.PackageReference:
                 case ReferenceType.Reference:
                     if (reference.MsbProject.GetItemsByEvaluatedInclude(unevaluatedInclude).Any())
                     {
                         output = false;
                     }
                     else
                     {
                         reference.MsbProject.AddItem(type.ToString(), unevaluatedInclude, AdaptMetadata(unevaluatedInclude, metadata));
                     }
                     break;
                 default:
                     throw new SwitcherException(reference.MsbProject, $"Reference type not supported: { type }");
             }
             if (output)
             {
                 MessageProvider.AddMessage(reference.MsbProject.FullPath, $"Dependency: { Path.GetFileName(unevaluatedInclude) } has been added. Type: { type }", MessageCategory.ME);
             }
             return output;
         }
References NuGetSwitcher.Core.Abstract.AbstractSwitch.AdaptMetadata(), NuGetSwitcher.Interface.Contract.IMessageProvider.AddMessage(), NuGetSwitcher.Core.Abstract.AbstractSwitch.MessageProvider, and NuGetSwitcher.Interface.Entity.IProjectReference.MsbProject.
GetLockFile()
virtual LockFile NuGetSwitcher.Core.Abstract.AbstractSwitch.GetLockFile (IProjectReference reference) protected virtual
Returns the LockFile object that represents the contents of project.assets.json. Used to identify project dependencies.
Exceptions
SwitcherFileNotFoundException
Definition at line 60 of file AbstractSwitch.cs.
         {
             return LockFileUtilities.GetLockFile(reference.GetLockFile(), NullLogger.Instance) ?? new LockFile();
         }
References NuGetSwitcher.Interface.Entity.IProjectReference.GetLockFile().
GetProjectTarget()
virtual LockFileTarget NuGetSwitcher.Core.Abstract.AbstractSwitch.GetProjectTarget (IProjectReference reference) protected virtual
Returns the LockFileTarget section for a project TFM from the lock file provided by LockFile.
Exceptions
SwitcherFileNotFoundException
Definition at line 72 of file AbstractSwitch.cs.
         {
             return GetLockFile(reference).GetTarget(new NuGetFramework(reference.TFI, new Version(reference.TFV), string.Empty), null) ??
                 new LockFileTarget()
                 {
                     Libraries = new List<LockFileTargetLibrary>()
                 };
         }
References NuGetSwitcher.Core.Abstract.AbstractSwitch.GetLockFile(), NuGetSwitcher.Interface.Entity.IProjectReference.TFI, and NuGetSwitcher.Interface.Entity.IProjectReference.TFV.
IterateAndExecute()
virtual void NuGetSwitcher.Core.Abstract.AbstractSwitch.IterateAndExecute (IEnumerable< IProjectReference > references, Action< IProjectReference, LockFileTargetLibrary, string > func) protected virtual
Iterates through the dependencies provided in the lock file and matches against items found in the directories listed in the configuration file. For each matched item, the passed delegate is executed.
Exceptions
SwitcherFileNotFoundException
FileNotFoundException
ArgumentException
Definition at line 101 of file AbstractSwitch.cs.
         {
             MessageProvider.Clear();
             ReadOnlyDictionary<string, string> items = OptionProvider.GetIncludeItems(Type);
             foreach (IProjectReference reference in references)
             {
                 foreach (LockFileTargetLibrary library in GetProjectTarget(reference).Libraries)
                 {
                     if (items.TryGetValue(library.Name, out string absolutePath))
                     {
                         func(reference, library, absolutePath);
                     }
                 }
                 reference.Save();
             }
         }
References NuGetSwitcher.Interface.Contract.IMessageProvider.Clear(), NuGetSwitcher.Interface.Contract.IOptionProvider.GetIncludeItems(), NuGetSwitcher.Core.Abstract.AbstractSwitch.GetProjectTarget(), NuGetSwitcher.Core.Abstract.AbstractSwitch.MessageProvider, NuGetSwitcher.Core.Abstract.AbstractSwitch.OptionProvider, NuGetSwitcher.Interface.Entity.IProjectReference.Save(), and NuGetSwitcher.Core.Abstract.AbstractSwitch.Type.
Switch()
abstract IEnumerable<string> NuGetSwitcher.Core.Abstract.AbstractSwitch.Switch () pure virtual
Basic operation of switching one type of reference to another.
Implemented in NuGetSwitcher.Core.Switch.ProjectSwitch, NuGetSwitcher.Core.Switch.LibrarySwitch, and NuGetSwitcher.Core.Switch.PackageSwitch.
Property Documentation
MessageProvider
IMessageProvider NuGetSwitcher.Core.Abstract.AbstractSwitch.MessageProvider get set protected
Definition at line 38 of file AbstractSwitch.cs.
         {
             get;
             set;
         }
OptionProvider
IOptionProvider NuGetSwitcher.Core.Abstract.AbstractSwitch.OptionProvider get set protected
Definition at line 26 of file AbstractSwitch.cs.
         {
             get;
             set;
         }
ProjectProvider
IProjectProvider NuGetSwitcher.Core.Abstract.AbstractSwitch.ProjectProvider get set protected
Definition at line 32 of file AbstractSwitch.cs.
         {
             get;
             set;
         }
Type
ReferenceType NuGetSwitcher.Core.Abstract.AbstractSwitch.Type get protected
Definition at line 20 of file AbstractSwitch.cs.
         {
             get;
             private set;
         }
The documentation for this class was generated from the following file:
NuGetSwitcher.Core/Abstract/AbstractSwitch.cs