NuGetSwitcher: NuGetSwitcher.Option.PackageOption Class Reference
NuGetSwitcher.Option.PackageOption Class Reference
Public Member Functions
void Init (IMessageHelper messageHelper)
virtual ReadOnlyDictionary< string, string > GetIncludeItems (ReferenceType type)
Returns a dictionary where file names are used as keys, and absolute file paths are values.
Protected Member Functions
virtual FileOption GetFileOption (ReferenceType type)
Returns the structure containing an array of directories to search for and directories to exclude from searches.
virtual bool Contains (string[] excludeDirectories, string absolutePath)
Returns true if a directory containing the file is found. Level at which the file is located is not taken into account.
Properties
string IncludeProjectFile [get, set]
For internal use only.
string IncludeLibraryFile [get, set]
For internal use only.
string ExcludeProjectFile [get, set]
For internal use only.
IMessageHelper MessageHelper [get, set]
Detailed Description
Definition at line 19 of file PackageOption.cs.
Member Function Documentation
Contains()
virtual bool NuGetSwitcher.Option.PackageOption.Contains (string [] excludeDirectories, string absolutePath) protected virtual
Returns true if a directory containing the file is found. Level at which the file is located is not taken into account.
Definition at line 137 of file PackageOption.cs.
         {
             const int NOT_FOUND = -1;
             return excludeDirectories.Any(d => absolutePath.IndexOf(d) != NOT_FOUND);
         }
GetFileOption()
virtual FileOption NuGetSwitcher.Option.PackageOption.GetFileOption (ReferenceType type) protected virtual
Returns the structure containing an array of directories to search for and directories to exclude from searches.
Exceptions
FileNotFoundException
ArgumentException
Definition at line 114 of file PackageOption.cs.
         {
             FileOption option;
             switch (type)
             {
                 case ReferenceType.ProjectReference:
                     option = new FileOption(IncludeProjectFile, ExcludeProjectFile, "*.csproj");
                     break;
                 case ReferenceType.Reference:
                     option = new FileOption(IncludeLibraryFile, ExcludeProjectFile, "*.dll");
                     break;
                 default: throw new ArgumentException($"Reference type not supported: { type }");
             }
             return option;
         }
References NuGetSwitcher.Option.PackageOption.ExcludeProjectFile, NuGetSwitcher.Option.PackageOption.IncludeLibraryFile, and NuGetSwitcher.Option.PackageOption.IncludeProjectFile.
GetIncludeItems()
virtual ReadOnlyDictionary<string, string> NuGetSwitcher.Option.PackageOption.GetIncludeItems (ReferenceType type) virtual
Returns a dictionary where file names are used as keys, and absolute file paths are values.
Exceptions
FileNotFoundException
ArgumentException
Implements NuGetSwitcher.Option.IPackageOption.
Definition at line 71 of file PackageOption.cs.
         {
             FileOption option = GetFileOption(type);
             Dictionary<string, string> output = new
             Dictionary<string, string>(30);
             foreach (string directory in option.Include)
             {
                 if (!Directory.Exists(directory))
                 {
                     MessageHelper.AddMessage($"Directory: { directory } does not exist and will be skipped", TaskErrorCategory.Warning);
                     continue;
                 }
                 foreach (string absolutePath in Directory.GetFiles(directory, option.Pattern, SearchOption.AllDirectories).Where(i => !Contains(option.Exclude, i)))
                 {
                     string key = Path.GetFileNameWithoutExtension(absolutePath);
                     if (!output.ContainsKey(key))
                     {
                         output.Add(key, absolutePath);
                     }
                     else
                     {
                         MessageHelper.AddMessage($"Project: { absolutePath } is a duplicate and will be skipped", TaskErrorCategory.Warning);
                     }
                 }
             }
             return new ReadOnlyDictionary<string, string>(output);
         }
References NuGetSwitcher.Helper.MessageHelper.AddMessage(), NuGetSwitcher.Option.PackageOption.Contains(), and NuGetSwitcher.Option.PackageOption.GetFileOption().
Init()
void NuGetSwitcher.Option.PackageOption.Init (IMessageHelper messageHelper)
Definition at line 57 of file PackageOption.cs.
         {
             MessageHelper = messageHelper;
         }
Property Documentation
ExcludeProjectFile
string NuGetSwitcher.Option.PackageOption.ExcludeProjectFile get set
For internal use only.
Definition at line 46 of file PackageOption.cs.
         {
             get;
             set;
         }
IncludeLibraryFile
string NuGetSwitcher.Option.PackageOption.IncludeLibraryFile get set
For internal use only.
Definition at line 36 of file PackageOption.cs.
         {
             get;
             set;
         }
IncludeProjectFile
string NuGetSwitcher.Option.PackageOption.IncludeProjectFile get set
For internal use only.
Definition at line 26 of file PackageOption.cs.
         {
             get;
             set;
         }
MessageHelper
IMessageHelper NuGetSwitcher.Option.PackageOption.MessageHelper get set protected
Definition at line 52 of file PackageOption.cs.
         {
             get;
             set;
         }
The documentation for this class was generated from the following file:
NuGetSwitcher.Option/PackageOption.cs