NuGetSwitcher: NuGetSwitcher.Abstract.AbstractSwitch Class Reference
NuGetSwitcher.Abstract.AbstractSwitch Class Reference abstract
Public Member Functions
abstract void Switch ()
Basic operation of switching one type of reference to another.
Protected Member Functions
AbstractSwitch (bool isVSIX, ReferenceType type, IPackageOption packageOption, IProjectHelper projectHelper, IMessageHelper messageHelper)
virtual void IterateAndExecute (IEnumerable< ProjectReference > references, Action< ProjectReference, LockFileTargetLibrary, string > func)
Iterates through the dependencies provided in the lock file and matches against items found in the directories listed in the configuration file. For each matched item, the passed delegate is executed.
virtual Dictionary< string, string > AdaptMetadata (string unevaluatedInclude, Dictionary< string, string > metadata)
Performs metadata validation and filling with data common to all references.
virtual bool AddReference (ProjectReference reference, ReferenceType type, string unevaluatedInclude, Dictionary< string, string > metadata)
Adds reference to the project. It is assumed that the original reference has been removed earlier.
Properties
bool IsVSIX [get]
Indicates that the call is from Visual Studio.
ReferenceType Type [get]
IPackageOption PackageOption [get, set]
IProjectHelper ProjectHelper [get, set]
IMessageHelper MessageHelper [get, set]
DTE DTE [get]
Returns the DTE object if the call is made from Visual Studio, otherwise null.
Detailed Description
Definition at line 22 of file AbstractSwitch.cs.
Constructor & Destructor Documentation
AbstractSwitch()
NuGetSwitcher.Abstract.AbstractSwitch.AbstractSwitch (bool isVSIX, ReferenceType type, IPackageOption packageOption, IProjectHelper projectHelper, IMessageHelper messageHelper) protected
Parameters
isVSIX Indicates that the call is from Visual Studio.
Definition at line 77 of file AbstractSwitch.cs.
         {
             IsVSIX = isVSIX;
             if (IsVSIX)
             {
                 DTE = Package.GetGlobalService(typeof(DTE)) as DTE;
             }
             Type = type;
             PackageOption = packageOption;
             ProjectHelper = projectHelper;
             MessageHelper = messageHelper;
         }
References NuGetSwitcher.Abstract.AbstractSwitch.DTE, NuGetSwitcher.Abstract.AbstractSwitch.IsVSIX, and NuGetSwitcher.Abstract.AbstractSwitch.Type.
Member Function Documentation
AdaptMetadata()
virtual Dictionary<string, string> NuGetSwitcher.Abstract.AbstractSwitch.AdaptMetadata (string unevaluatedInclude, Dictionary< string, string > metadata) protected virtual
Performs metadata validation and filling with data common to all references.
See:
See also
AddReference(ProjectReference, ReferenceType, string, Dictionary<string, string>)
.
Definition at line 141 of file AbstractSwitch.cs.
         {
             if (!metadata.ContainsKey("Temp"))
             {
                 metadata.Add("Temp", unevaluatedInclude);
             }
             return metadata;
         }
AddReference()
virtual bool NuGetSwitcher.Abstract.AbstractSwitch.AddReference (ProjectReference reference, ReferenceType type, string unevaluatedInclude, Dictionary< string, string > metadata) protected virtual
Adds reference to the project. It is assumed that the original reference has been removed earlier.
Parameters
unevaluatedInclude Must contain the assembly name or the absolute path to the project or Package Id.
Exceptions
SwitcherException
Returns
Returns false for duplicate unevaluatedInclude values.
Definition at line 169 of file AbstractSwitch.cs.
         {
             bool output = true;
             switch (type)
             {
                 case ReferenceType.ProjectReference:
                 case ReferenceType.PackageReference:
                 case ReferenceType.Reference:
                     if (reference.MsbProject.GetItemsByEvaluatedInclude(unevaluatedInclude).Any())
                     {
                         output = false;
                     }
                     else
                     {
                         reference.MsbProject.AddItem(type.ToString(), unevaluatedInclude, AdaptMetadata(unevaluatedInclude, metadata));
                     }
                     break;
                 default:
                     throw new SwitcherException(reference.MsbProject, $"Reference type not supported: { type }");
             }
             if (output)
             {
                 MessageHelper.AddMessage(reference.DteProject.UniqueName, $"Dependency: { Path.GetFileName(unevaluatedInclude) } has been added. Type: { type }", TaskErrorCategory.Message);
             }
             return output;
         }
References NuGetSwitcher.Abstract.AbstractSwitch.AdaptMetadata(), NuGetSwitcher.Helper.MessageHelper.AddMessage(), NuGetSwitcher.Helper.Entity.ProjectReference.DteProject, and NuGetSwitcher.Helper.Entity.ProjectReference.MsbProject.
IterateAndExecute()
virtual void NuGetSwitcher.Abstract.AbstractSwitch.IterateAndExecute (IEnumerable< ProjectReference > references, Action< ProjectReference, LockFileTargetLibrary, string > func) protected virtual
Iterates through the dependencies provided in the lock file and matches against items found in the directories listed in the configuration file. For each matched item, the passed delegate is executed.
Exceptions
SwitcherFileNotFoundException
FileNotFoundException
ArgumentException
Definition at line 112 of file AbstractSwitch.cs.
         {
             MessageHelper.Clear();
             ReadOnlyDictionary<string, string> items = PackageOption.GetIncludeItems(Type);
             foreach (ProjectReference reference in references)
             {
                 foreach (LockFileTargetLibrary library in PackageHelper.GetProjectTarget(reference).Libraries)
                 {
                     if (items.TryGetValue(library.Name, out string absolutePath))
                     {
                         func(reference, library, absolutePath);
                     }
                 }
                 reference.Save();
             }
         }
References NuGetSwitcher.Helper.MessageHelper.Clear(), NuGetSwitcher.Option.PackageOption.GetIncludeItems(), NuGetSwitcher.Helper.PackageHelper.GetProjectTarget(), NuGetSwitcher.Helper.Entity.ProjectReference.Save(), and NuGetSwitcher.Abstract.AbstractSwitch.Type.
Switch()
abstract void NuGetSwitcher.Abstract.AbstractSwitch.Switch () pure virtual
Basic operation of switching one type of reference to another.
Implemented in NuGetSwitcher.Core.Switch.ProjectSwitch, NuGetSwitcher.Core.Switch.PackageSwitch, and NuGetSwitcher.Core.Switch.LibrarySwitch.
Property Documentation
DTE
DTE NuGetSwitcher.Abstract.AbstractSwitch.DTE get protected
Returns the DTE object if the call is made from Visual Studio, otherwise null.
DTE - Development Tools Environment. See: https://www.viva64.com/en/a/0082/#ID4ED3F15B53.
Definition at line 68 of file AbstractSwitch.cs.
         {
             get;
             private set;
         }
IsVSIX
bool NuGetSwitcher.Abstract.AbstractSwitch.IsVSIX get protected
Indicates that the call is from Visual Studio.
Definition at line 29 of file AbstractSwitch.cs.
         {
             get;
             private set;
         }
MessageHelper
IMessageHelper NuGetSwitcher.Abstract.AbstractSwitch.MessageHelper get set protected
Definition at line 53 of file AbstractSwitch.cs.
         {
             get;
             set;
         }
PackageOption
IPackageOption NuGetSwitcher.Abstract.AbstractSwitch.PackageOption get set protected
Definition at line 41 of file AbstractSwitch.cs.
         {
             get;
             set;
         }
ProjectHelper
IProjectHelper NuGetSwitcher.Abstract.AbstractSwitch.ProjectHelper get set protected
Definition at line 47 of file AbstractSwitch.cs.
         {
             get;
             set;
         }
Type
ReferenceType NuGetSwitcher.Abstract.AbstractSwitch.Type get protected
Definition at line 35 of file AbstractSwitch.cs.
         {
             get;
             private set;
         }
The documentation for this class was generated from the following file:
NuGetSwitcher.Abstract/AbstractSwitch.cs