NuGetSwitcher: NuGetSwitcher.Helper.MessageHelper Class Reference
NuGetSwitcher.Helper.MessageHelper Class Reference
Public Member Functions
MessageHelper (IVsSolution vsSolution, ErrorListProvider errorList)
virtual void AddMessage (string message, TaskErrorCategory category, [CallerMemberName] string caller="")
Displays a message with the specified type in the associated GUI tab.
virtual void AddMessage (string project, string message, TaskErrorCategory category, [CallerMemberName] string caller="")
Displays a message with the specified type in the associated GUI tab. This overload fills the Project column.
virtual void AddMessage (Exception exception, [CallerMemberName] string caller="")
Displays a message with the specified type in the associated GUI tab.
virtual void AddMessage (string project, Exception exception, [CallerMemberName] string caller="")
Displays a message with the specified type in the associated GUI tab. This overload fills the Project column.
virtual void AddMessage (SwitcherException exception, [CallerMemberName] string caller="")
Displays a message with the specified type in the associated GUI tab.
virtual void Clear ()
Clears previously created tasks in ErrorListProvider.
Protected Member Functions
virtual IVsHierarchy GetProjectHierarchyItem (string project)
Returns the project in the solution, given a unique name.
Properties
IVsSolution VsSolution [get, set]
ErrorListProvider ErrorList [get, set]
Detailed Description
Definition at line 11 of file MessageHelper.cs.
Constructor & Destructor Documentation
MessageHelper()
NuGetSwitcher.Helper.MessageHelper.MessageHelper (IVsSolution vsSolution, ErrorListProvider errorList)
Definition at line 25 of file MessageHelper.cs.
         {
             VsSolution = vsSolution;
             ErrorList = errorList;
         }
References NuGetSwitcher.Helper.MessageHelper.ErrorList, and NuGetSwitcher.Helper.MessageHelper.VsSolution.
Member Function Documentation
AddMessage() [1/5]
virtual void NuGetSwitcher.Helper.MessageHelper.AddMessage (string message, TaskErrorCategory category, [CallerMemberName] string caller = "") virtual
Displays a message with the specified type in the associated GUI tab.
Implements NuGetSwitcher.Helper.IMessageHelper.
Definition at line 37 of file MessageHelper.cs.
         {
             ErrorList.Tasks.Add(new ErrorTask { Text = $"Caller: { caller }. Message: { message }", ErrorCategory = category });
         }
References NuGetSwitcher.Helper.MessageHelper.ErrorList.
AddMessage() [2/5]
virtual void NuGetSwitcher.Helper.MessageHelper.AddMessage (string project, string message, TaskErrorCategory category, [CallerMemberName] string caller = "") virtual
Displays a message with the specified type in the associated GUI tab. This overload fills the Project column.
Parameters
project Full path to the solution project.
Implements NuGetSwitcher.Helper.IMessageHelper.
Definition at line 53 of file MessageHelper.cs.
         {
             ErrorList.Tasks.Add(new ErrorTask { Text = $"Caller: { caller }. Message: { message }", ErrorCategory = category, HierarchyItem = GetProjectHierarchyItem(project), Document = project });
         }
References NuGetSwitcher.Helper.MessageHelper.ErrorList, and NuGetSwitcher.Helper.MessageHelper.GetProjectHierarchyItem().
AddMessage() [3/5]
virtual void NuGetSwitcher.Helper.MessageHelper.AddMessage (Exception exception, [CallerMemberName] string caller = "") virtual
Displays a message with the specified type in the associated GUI tab.
Implements NuGetSwitcher.Helper.IMessageHelper.
Definition at line 63 of file MessageHelper.cs.
         {
             SwitcherException se = exception as SwitcherException;
             if (se == default)
             {
                 AddMessage(exception.Message, TaskErrorCategory.Error, caller);
             }
             else
             {
                 AddMessage(se);
             }
         }
References NuGetSwitcher.Helper.MessageHelper.AddMessage().
AddMessage() [4/5]
virtual void NuGetSwitcher.Helper.MessageHelper.AddMessage (string project, Exception exception, [CallerMemberName] string caller = "") virtual
Displays a message with the specified type in the associated GUI tab. This overload fills the Project column.
Parameters
project Full path to the solution project.
Implements NuGetSwitcher.Helper.IMessageHelper.
Definition at line 88 of file MessageHelper.cs.
         {
             AddMessage(project, exception.Message, TaskErrorCategory.Error, caller);
         }
References NuGetSwitcher.Helper.MessageHelper.AddMessage().
AddMessage() [5/5]
virtual void NuGetSwitcher.Helper.MessageHelper.AddMessage (SwitcherException exception, [CallerMemberName] string caller = "") virtual
Displays a message with the specified type in the associated GUI tab.
Implements NuGetSwitcher.Helper.IMessageHelper.
Definition at line 98 of file MessageHelper.cs.
         {
             AddMessage(exception.MsbProject.FullPath, exception.Message, TaskErrorCategory.Error, caller);
         }
References NuGetSwitcher.Helper.MessageHelper.AddMessage(), and NuGetSwitcher.Helper.Entity.Error.SwitcherException.MsbProject.
Clear()
virtual void NuGetSwitcher.Helper.MessageHelper.Clear () virtual
Clears previously created tasks in ErrorListProvider.
Implements NuGetSwitcher.Helper.IMessageHelper.
Definition at line 107 of file MessageHelper.cs.
         {
             ErrorList.Tasks.Clear();
         }
References NuGetSwitcher.Helper.MessageHelper.ErrorList.
GetProjectHierarchyItem()
virtual IVsHierarchy NuGetSwitcher.Helper.MessageHelper.GetProjectHierarchyItem (string project) protected virtual
Returns the project in the solution, given a unique name.
Parameters
project Full path to the solution project.
Returns
Pointer to the IVsHierarchy interface of the project referred to by project.
https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.shell.interop.ivshierarchy.
Definition at line 129 of file MessageHelper.cs.
         {
             const int S_OK = 0;
             ThreadHelper.ThrowIfNotOnUIThread();
             int exitCode = VsSolution.GetProjectOfUniqueName(project, out IVsHierarchy hierarchyItem);
             if (exitCode != S_OK)
             {
                 AddMessage($"Exit code: { exitCode }", TaskErrorCategory.Error);
             }
             return hierarchyItem;
         }
References NuGetSwitcher.Helper.MessageHelper.AddMessage(), and NuGetSwitcher.Helper.MessageHelper.VsSolution.
Property Documentation
ErrorList
ErrorListProvider NuGetSwitcher.Helper.MessageHelper.ErrorList get set protected
Definition at line 20 of file MessageHelper.cs.
         {
             get;
             set;
         }
VsSolution
IVsSolution NuGetSwitcher.Helper.MessageHelper.VsSolution get set protected
Definition at line 14 of file MessageHelper.cs.
         {
             get;
             set;
         }
The documentation for this class was generated from the following file:
NuGetSwitcher.Helper/MessageHelper.cs