NuGetSwitcher: NuGetSwitcher.Helper.ProjectHelper Class Reference
NuGetSwitcher.Helper.ProjectHelper Class Reference
Public Member Functions
ProjectHelper ()
virtual IEnumerable< ProjectReference > GetLoadedProject ()
Returns solution projects that are also loaded into the GPC.
virtual IEnumerable< Project > GetLoadedProject (IEnumerable< string > projects)
Returns projects from GPC.
virtual Project GetLoadedProject (string project)
Returns projects from GPC.
virtual void UnloadProject ()
Unloads projects from GPC.
virtual void UnloadProject (Project project)
Unloads projects from GPC.
virtual void UnloadProject (string project)
Unloads projects from GPC.
Properties
EnvDTE.DTE DTE [get, set]
Detailed Description
Definition at line 14 of file ProjectHelper.cs.
Constructor & Destructor Documentation
ProjectHelper()
NuGetSwitcher.Helper.ProjectHelper.ProjectHelper ()
Definition at line 22 of file ProjectHelper.cs.
         {
             DTE = Package.GetGlobalService(typeof(EnvDTE.DTE)) as EnvDTE.DTE;
         }
References NuGetSwitcher.Helper.ProjectHelper.DTE.
Member Function Documentation
GetLoadedProject() [1/3]
virtual IEnumerable<ProjectReference> NuGetSwitcher.Helper.ProjectHelper.GetLoadedProject () virtual
Returns solution projects that are also loaded into the GPC.
Implements NuGetSwitcher.Helper.IProjectHelper.
Definition at line 32 of file ProjectHelper.cs.
         {
             List<ProjectReference> projects = new
             List<ProjectReference>(30);
             foreach (EnvDTE.Project dteProject in DTE.Solution.Projects)
             {
                 // To filter miscellaneous files.
                 if (string.IsNullOrWhiteSpace(dteProject.FileName))
                 {
                     continue;
                 }
                 projects.Add(new ProjectReference(dteProject, GetLoadedProject(dteProject.FullName)));
             }
             return projects;
         }
References NuGetSwitcher.Helper.ProjectHelper.DTE.
GetLoadedProject() [2/3]
virtual IEnumerable<Project> NuGetSwitcher.Helper.ProjectHelper.GetLoadedProject (IEnumerable< string > projects) virtual
Returns projects from GPC.
Implements NuGetSwitcher.Helper.IProjectHelper.
Definition at line 54 of file ProjectHelper.cs.
         {
             return projects.Select(p => GetLoadedProject(p));
         }
References NuGetSwitcher.Helper.ProjectHelper.GetLoadedProject().
GetLoadedProject() [3/3]
virtual Project NuGetSwitcher.Helper.ProjectHelper.GetLoadedProject (string project) virtual
Returns projects from GPC.
Implements NuGetSwitcher.Helper.IProjectHelper.
Definition at line 62 of file ProjectHelper.cs.
         {
             return ProjectCollection.GlobalProjectCollection.LoadProject(project);
         }
UnloadProject() [1/3]
virtual void NuGetSwitcher.Helper.ProjectHelper.UnloadProject () virtual
Unloads projects from GPC.
Implements NuGetSwitcher.Helper.IProjectHelper.
Definition at line 70 of file ProjectHelper.cs.
         {
             ProjectCollection.GlobalProjectCollection.UnloadAllProjects();
         }
UnloadProject() [2/3]
virtual void NuGetSwitcher.Helper.ProjectHelper.UnloadProject (Project project) virtual
Unloads projects from GPC.
Exceptions
SwitcherInvalidOperationException
Implements NuGetSwitcher.Helper.IProjectHelper.
Definition at line 80 of file ProjectHelper.cs.
         {
             try
             {
                 ProjectCollection.GlobalProjectCollection.UnloadProject(project);
             }
             catch (InvalidOperationException exception)
             {
                 throw new SwitcherInvalidOperationException(project, exception);
             }
         }
UnloadProject() [3/3]
virtual void NuGetSwitcher.Helper.ProjectHelper.UnloadProject (string project) virtual
Unloads projects from GPC.
Exceptions
SwitcherInvalidOperationException
Implements NuGetSwitcher.Helper.IProjectHelper.
Definition at line 97 of file ProjectHelper.cs.
         {
             UnloadProject(GetLoadedProject(project));
         }
References NuGetSwitcher.Helper.ProjectHelper.GetLoadedProject(), and NuGetSwitcher.Helper.ProjectHelper.UnloadProject().
Property Documentation
DTE
EnvDTE.DTE NuGetSwitcher.Helper.ProjectHelper.DTE get set protected
Definition at line 17 of file ProjectHelper.cs.
         {
             get;
             set;
         }
The documentation for this class was generated from the following file:
NuGetSwitcher.Helper/ProjectHelper.cs