name: 'Build'
'on':
  push:
    branches:
      - 'develop'
      - 'master'

jobs:
  build:

    runs-on: 'windows-latest'

    env:
      RepositoryUrl: 'https://github.com/${{ github.repository }}'
      RepositoryBranch: '${{ github.ref }}'
      SourceRevisionId: '${{ github.sha }}'

    steps:
      - name: 'Checkout repository'
        uses: 'actions/checkout@v2'


      - name: 'Setup .NET'
        uses: 'actions/setup-dotnet@v1'
        with:
          dotnet-version: 5.0.x
      
      
      - name: 'Setup MSBuild'
        uses: 'microsoft/setup-msbuild@v1.1'
      
      
      - name: 'Build'
        run : 'msbuild NuGetSwitcher.sln /t:Restore /t:Rebuild -property:Configuration=Release'